// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace OnlinePizzaApi.Models;

public partial class Register
{
    public string Uname { get; set; }

    public string Password { get; set; }

    public bool? Gender { get; set; }

    public DateTime? Dob { get; set; }

    public string Email { get; set; }
}