// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace OnlinePizzaApi.Models;

public partial class pizzadbContext : DbContext
{
    public pizzadbContext()
    {
    }

    public pizzadbContext(DbContextOptions<pizzadbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Pizza> Pizzas { get; set; }

    public virtual DbSet<Register> Registers { get; set; }

    public virtual DbSet<Userorder> Userorders { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=WKSBAN36KELTR19\\SQLEXPRESS;Initial Catalog=pizzaonline;Integrated Security=True;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Pizza>(entity =>
        {
            entity.HasKey(e => e.Pizzaid).HasName("PK__pizza__4D4B9487B8F08C2F");

            entity.ToTable("pizza");

            entity.Property(e => e.Pizzaid)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("pizzaid");
            entity.Property(e => e.Description)
                .HasMaxLength(90)
                .IsUnicode(false)
                .HasColumnName("description");
            entity.Property(e => e.Pimage)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("pimage");
            entity.Property(e => e.Pizzaname)
                .HasMaxLength(40)
                .IsUnicode(false)
                .HasColumnName("pizzaname");
            entity.Property(e => e.Price).HasColumnName("price");
        });

        modelBuilder.Entity<Register>(entity =>
        {
            entity.HasKey(e => e.Uname).HasName("PK__Register__C7D2484FB947D8A1");

            entity.ToTable("Register");

            entity.Property(e => e.Uname)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("uname");
            entity.Property(e => e.Dob)
                .HasColumnType("datetime")
                .HasColumnName("DOB");
            entity.Property(e => e.Email)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("email");
            entity.Property(e => e.Gender).HasColumnName("gender");
            entity.Property(e => e.Password)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("password");
        });

        modelBuilder.Entity<Userorder>(entity =>
        {
            entity.HasKey(e => e.Tranid).HasName("PK__userorde__9A599E03DE9967CD");

            entity.ToTable("userorders");

            entity.Property(e => e.Tranid).HasColumnName("tranid");
            entity.Property(e => e.Pizzaid)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("pizzaid");
            entity.Property(e => e.Qty).HasColumnName("qty");
            entity.Property(e => e.Transdate).HasColumnName("transdate");
            entity.Property(e => e.Username)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("username");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}